services:
  reachable:
    image: ghcr.io/reachableapps/reachable:latest
    pull_policy: always
    container_name: reachable
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - reachable_data:/var/www/html/storage
      - reachable_postgres_data:/var/lib/postgresql/data
      - reachable_redis_data:/data

volumes:
  reachable_data:
  reachable_postgres_data:
  reachable_redis_data:
