services:
  reachable:
    image: ghcr.io/ryzenixx/reachable:latest
    pull_policy: always
    container_name: reachable
    restart: unless-stopped
    environment:
      REACHABLE_DOMAIN: ${REACHABLE_DOMAIN:-reachable.localhost}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-CHANGEME}
    ports:
      - "3000:80"
    volumes:
      - reachable_data:/var/www/html/storage
      - reachable_postgres_data:/var/lib/postgresql/data
      - reachable_redis_data:/data

volumes:
  reachable_data:
  reachable_postgres_data:
  reachable_redis_data:
