global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  file:
    filename: /etc/traefik/dynamic.yml

certificatesResolvers:
  le:
    acme:
      email: certs@reachable.dev
      storage: /var/www/html/storage/traefik/acme.json
      httpChallenge:
        entryPoint: web
